spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greetings-in:
          destination: greetings
          content-Type: application/json
        greetings-out:
          destination: greetings
          content-Type: application/json
